### ISSUE TITLE
WS Connection error: Ws(Protocol(ResetWithoutClosingHandshake))

### ISSUE THREAD

**Issue by holmofy** [lightpanda-io/browser#1160]
Thanks to the awesome lightpanda. I'm using the Rust community's [chromiumoxide](https://github.com/mattsse/chromiumoxide) to connect to lightpanda, but I can't connect to lightpanda. 

Below is my code repository: 

* https://github.com/AutoWDS/autowds-instance

https://github.com/mattsse/chromiumoxide/issues/267

**Comment by krichprollsch** [comment]
Hello @holmofy,
Thanks for your issue.

I'm using a CDP proxy to dump the messages exchanged between your project and Lightpanda.
A first issue is chromiumxide uses `Security.setIgnoreCertificateErrors` which is not implemented on Lightpanda.
I will try to fix it first and see if it unblocks you.

```
> {"id":10,"method":"Security.setIgnoreCertificateErrors","sessionId":"SID-1","params":{"ignore":true}}
< {"id":10,"error":{"code":-31998,"message":"UnknownMethod"},"sessionId":"SID-1"}
```

**Comment by krichprollsch** [comment]
Another issue I can see is we don't support `url` in createTarget for now (see https://github.com/lightpanda-io/browser/blob/main/src/cdp/domains/target.zig#L112).

I will take a look at this 👀 

```
> {"id":1,"method":"Target.createTarget","params":{"url":"https://en.wikipedia.org"}}
```

**Comment by krichprollsch** [comment]
A third issue is when we run `find_element`:
```
2025-10-21T15:58:29.397592Z ERROR autowds_instance: 💥 Browser session error: Node is either not visible or not an HTMLElement
```

It's due to a `false` result of this JS script eval:

```
> {"id":19,"method":"Runtime.callFunctionOn","sessionId":"SID-1","params":{"awaitPromise":true,"functionDeclaration":"async function() {\n                if (!this.isConnected)\n                    return 'Node is detached from document';\n                if (this.nodeType !== Node.ELEMENT_NODE)\n                    return 'Node is not of type HTMLElement';\n\n                const visibleRatio = await new Promise(resolve => {\n                    const observer = new IntersectionObserver(entries => {\n                        resolve(entries[0].intersectionRatio);\n                        observer.disconnect();\n                    });\n                    observer.observe(this);\n                });\n\n                if (visibleRatio !== 1.0)\n                    this.scrollIntoView({\n                        block: 'center',\n                        inline: 'center',\n                        behavior: 'instant'\n                    });\n                return false;\n            }","generatePreview":true,"objectId":"5987356902031041503.1.1"}}
< {"id":19,"result":{"result":{"type":"boolean","value":false}},"sessionId":"SID-1"}
```

```javascript
async function() {
    if (!this.isConnected)
        return 'Node is detached from document';
    if (this.nodeType !== Node.ELEMENT_NODE)
        return 'Node is not of type HTMLElement';

    const visibleRatio = await new Promise(resolve => {
        const observer = new IntersectionObserver(entries => {
            resolve(entries[0].intersectionRatio);
            observer.disconnect();
        });
        observer.observe(this);
    });

    if (visibleRatio !== 1.0)
        this.scrollIntoView({
            block: 'center',
            inline: 'center',
            behavior: 'instant'
        });
    return false;
}
````

**Comment by krichprollsch** [comment]
I was wrong, chrome returns same result:
```
< {"id":32,"result":{"result":{"type":"boolean","value":false}},"sessionId":"BD65E0B6BD0B390281E58E112EF46B48"}
```

**Comment by krichprollsch** [comment]
I guess it's due to the fake coordinates we return:
```
> {"id":20,"method":"DOM.getContentQuads","sessionId":"SID-1","params":{"backendNodeId":4}}
< {"id":20,"result":{"quads":[[0,0,1,0,1,1,0,1]]},"sessionId":"SID-1"}
```

vs. chrome
```
> {"id":33,"method":"DOM.getContentQuads","sessionId":"BD65E0B6BD0B390281E58E112EF46B48","params":{"backendNodeId":15}}
< {"id":33,"result":{"quads":[[306,17,710.296875,17,710.296875,49,306,49]]},"sessionId":"BD65E0B6BD0B390281E58E112EF46B48"}
```

The code from chromiumoxide
```rs
        content_quads
            .quads
            .iter()
            .filter(|q| q.inner().len() == 8)
            .map(ElementQuad::from_quad)
            .filter(|q| q.quad_area() > 1.)
            .map(|q| q.quad_center())
            .next()
            .ok_or_else(|| CdpError::msg("Node is either not visible or not an HTMLElement"))
```
https://github.com/mattsse/chromiumoxide/blob/main/src/element.rs#L150-L158
I guess our area is equals to 1? so we fall in the else case?

**Comment by krichprollsch** [comment]
@holmofy I merged the last change today.
It seems I have similar result than chrome now, but let-me know if anything still blocks.
It will be part of the nightly build by tomorrow.

I will add a [chromiumoxide](https://github.com/mattsse/chromiumoxide) example in our end to end tests.

**Comment by holmofy** [comment]
I'm still having problems running my code with a nightly version of Lightpanda in Docker.

**Comment by krichprollsch** [comment]
Hello @holmofy 
Thnks for your patience, I will try it next week.

**Comment by krichprollsch** [comment]
ok, I created #1231 which should fix the search issues with click+input fill w/ wikipedia

**Comment by krichprollsch** [comment]
@holmofy can you give another try please?
