### ISSUE TITLE
the example used in the readme does not work

### ISSUE THREAD

**Issue by frankgreco** [lightpanda-io/browser#379]
The hello world example does not work. In fact, no website I've tried works. It's usually always panics. 
```
./lightpanda-aarch64-macos --host 127.0.0.1 --port 9222
info(websocket): starting blocking worker to listen on 127.0.0.1:9222
info(server): accepting new conn...
info(server): client connected
info(browser): GET https://wikipedia.com/ 200
info(browser): fetch [https://wikipedia.com/portal/wikipedia.org/assets/js/index-2...](https://wikipedia.com/portal/wikipedia.org/assets/js/index-24c3e2ca18.js): http.Status.ok
info(browser): eval script portal/wikipedia.org/assets/js/index-24c3e2ca18.js: ReferenceError: location is not defined
info(browser): fetch [https://wikipedia.com/portal/wikipedia.org/assets/js/gt-ie9-...](https://wikipedia.com/portal/wikipedia.org/assets/js/gt-ie9-ce3fe8e88d.js): http.Status.ok
error(events): event handler error: error.JSExecCallback
info(events): event handler error try catch: TypeError: Cannot read properties of undefined (reading 'length')
info(server): close cmd, closing conn...
info(server): accepting new conn...
thread 5274880 panic: attempt to use null value
zsh: abort ./lightpanda-aarch64-macos --host 127.0.0.1 --port 9222
```

**Comment by krichprollsch** [comment]
Hello @frankgreco,
Thanks for the issue.
Indeed I can reproduce, something goes wrong on handling the client's disconnection.

But I get the list of the links correctly. Did you get them?

**Comment by frankgreco** [comment]
If I try to dump the page contents, I get a different error.

```javascript
'use strict'

import puppeteer from 'puppeteer-core';

const browser = await puppeteer.connect({
  browserWSEndpoint: "ws://127.0.0.1:9222",
});

const context = await browser.createBrowserContext();
const page = await context.newPage();

await page.goto('https://wikipedia.com/');

console.log(await page.content());

await page.close();
await context.close();
```
```
❯ node index.mjs
file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:77
            this._reject(callback, new TargetCloseError('Target closed'));
                                   ^

TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
    at CallbackRegistry.clear (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:77:36)
    at CdpCDPSession._onClosed (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:106:25)
    at #onClose (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:171:21)
    at WebSocket.<anonymous> (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:43:30)
    at callListener (/Users/frank/projects/superblocks/browser/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/Users/frank/projects/superblocks/browser/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:520:28)
    at WebSocket.emitClose (/Users/frank/projects/superblocks/browser/node_modules/ws/lib/websocket.js:272:10)
    at Socket.socketOnClose (/Users/frank/projects/superblocks/browser/node_modules/ws/lib/websocket.js:1341:15)
    at Socket.emit (node:events:520:28) {
  cause: ProtocolError
      at <instance_members_initializer> (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:97:14)
      at new Callback (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:101:16)
      at CallbackRegistry.create (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:20:26)
      at Connection._rawSend (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:89:26)
      at CdpCDPSession.send (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:66:33)
      at #evaluate (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:359:50)
      at ExecutionContext.evaluate (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:274:36)
      at IsolatedWorld.evaluate (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:97:30)
      at CdpFrame.evaluate (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/api/Frame.js:345:43)
      at CdpFrame.<anonymous> (file:///Users/frank/projects/superblocks/browser/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:101:27)
}

Node.js v22.6.0
```
```
❯ ./lightpanda-aarch64-macos --host 127.0.0.1 --port 9222
info(websocket): starting blocking worker to listen on 127.0.0.1:9222
info(server): accepting new conn...
info(server): client connected
info(browser): GET https://wikipedia.com/ 200
info(browser): fetch https://wikipedia.com/portal/wikipedia.org/assets/js/index-24c3e2ca18.js: http.Status.ok
info(browser): eval script portal/wikipedia.org/assets/js/index-24c3e2ca18.js: ReferenceError: location is not defined
info(browser): fetch https://wikipedia.com/portal/wikipedia.org/assets/js/gt-ie9-ce3fe8e88d.js: http.Status.ok
error(events): event handler error: error.JSExecCallback
info(events): event handler error try catch: TypeError: Cannot read properties of undefined (reading 'length')
info(server): close cmd, closing conn...
info(server): accepting new conn...
thread 5774907 panic: attempt to use null value
zsh: abort      ./lightpanda-aarch64-macos --host 127.0.0.1 --port 9222
```

**Comment by sanjomathew09** [comment]
'use strict';

import puppeteer from 'puppeteer-core';

async function main() {
  try {
    // Connect to the browser instance
    const browser = await puppeteer.connect({
      browserWSEndpoint: 'ws://127.0.0.1:9222', // WebSocket endpoint
    });

    // Create a new browser context (isolation)
    const context = await browser.createIncognitoBrowserContext(); // Use incognito mode for a clean session

    // Open a new page in the context
    const page = await context.newPage();

    // Navigate to the target URL
    await page.goto('https://wikipedia.com/', {
      waitUntil: 'networkidle2', // Wait for network to be idle
    });

    // Extract the page content
    const pageContent = await page.content();
    console.log(pageContent);

    // Clean up
    await page.close(); // Close the page
    await context.close(); // Close the browser context
    await browser.disconnect(); // Disconnect from the browser
  } catch (error) {
    console.error('An error occurred:', error);
  }
}

main();

**Comment by ManojBhamsagar-Draup** [comment]
Yes I'm also stuck with the same error:


const context = await browser.createBrowserContext();
                              ^

TypeError: browser.createBrowserContext is not a function

At least, please provide a minimal example that works. Since this repo lacks documentation.

**Comment by frankgreco** [comment]
@sanjomathew09 Your code yields ⬇ 
```
info(browser): GET https://wikipedia.com/ 200
info(browser): fetch https://wikipedia.com/portal/wikipedia.org/assets/js/index-6bf78c58fd.js: http.Status.ok
info(browser): eval script portal/wikipedia.org/assets/js/index-6bf78c58fd.js: ReferenceError: location is not defined
info(browser): fetch https://wikipedia.com/portal/wikipedia.org/assets/js/gt-ie9-ce3fe8e88d.js: http.Status.ok
error(events): event handler error: error.JSExecCallback
info(events): event handler error try catch: TypeError: Cannot read properties of undefined (reading 'length')
```

Ideally just looking for a minimal hello world. I see that this project gets a lot of development so I'm assuming that there's a way to get it to work.

**Comment by krichprollsch** [comment]
@frankgreco I merged an improvement regarding the bug you had.
Can you re-test your script to dump html w/ puppeteer please?

**Comment by bruvduroiu** [comment]
Still seeing this error building for `linux/amd64` via the Dockerfile, same script as the README file

```
≫ git rev-parse HEAD
43f42f9ca009dfff37ca703f3d72fee6e1dbfe88
```

```
info(server): client connected                                                                                                                                                                                                                          
info(browser): GET https://wikipedia.org/ 200                                                                                                                                                                                                           
info(browser): fetch https://wikipedia.org/portal/wikipedia.org/assets/js/index-6bf78c58fd.js: http.Status.ok                                                                                                                                           
info(browser): eval script portal/wikipedia.org/assets/js/index-6bf78c58fd.js: Error: NotImplemented                                                                                                                                                    
info(browser): fetch https://wikipedia.org/portal/wikipedia.org/assets/js/gt-ie9-ce3fe8e88d.js: http.Status.ok                                                                                                                                          
error(events): event handler error: error.JSExecCallback                                                                                                                                                                                                
info(events): event handler error try catch: TypeError: Cannot read properties of undefined (reading 'length')
```

EDIT: I should mention that I'm waiting for `networkidle0` when fetching Wikipedia

**Comment by krichprollsch** [comment]
@bruvduroiu thanks for your feedback.
The errors are JS error due to Web APIs missing in Ligthpanda.
They shouldn't block the browser's execution, but the final result may not be exactly the expected one.

**Comment by gianpaj** [comment]
I'm not sure if it's the same issue, but `lightpanda` is crashing when I fetch this page (angular 1.x site) using Puppeteer

```
$ ./lightpanda

$time=399671355 $scope=user_script $level=warn $msg="eval script" url=https://js.hubspot.com/web-interactives-embed.js err="TypeError: Cannot read properties of null (reading 'data')" cacheable=true
$time=399671451 $scope=console $level=warn $msg=warn args="; 1: Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading"
$time=399671463 $scope=console $level=warn $msg=error args="; 1: The Google Maps JavaScript API does not support this browser. See https://developers.google.com/maps/documentation/javascript/error-messages#unsupported-browsers" stack=null
Segmentation fault at address 0x0
???:?:?: 0x1045c9f48 in _locale_charset (???)
???:?:?: 0x105dffe23 in _browser.js.Context.valueToString (???)
???:?:?: 0x105def64f in _browser.js.Env.promiseRejectCallback (???)
???:?:?: 0x10471950f in _locale_charset (???)
???:?:?: 0x104befb9b in _locale_charset (???)
???:?:?: 0x105b69073 in _locale_charset (???)
???:?:?: 0x105bd852f in _locale_charset (???)
???:?:?: 0x105ac5c3f in _locale_charset (???)
???:?:?: 0x105bde5f7 in _locale_charset (???)
???:?:?: 0x105af40b7 in _locale_charset (???)
???:?:?: 0x105ac2ef3 in _locale_charset (???)
???:?:?: 0x1046f9b6f in _locale_charset (???)
???:?:?: 0x1046fa4bb in _locale_charset (???)
???:?:?: 0x1046fa60b in _locale_charset (???)
???:?:?: 0x104727d93 in _locale_charset (???)
???:?:?: 0x104727bef in _locale_charset (???)
???:?:?: 0x105e61583 in _cdp.cdp.BrowserContext(cdp.cdp.CDPT(cdp.cdp.CDP__struct_41726)).deinit (???)
???:?:?: 0x105e32477 in _cdp.cdp.CDPT(cdp.cdp.CDP__struct_41726).dispatchCommand__anon_99632 (???)
???:?:?: 0x105df1bff in _server.Client.processData (???)
???:?:?: 0x105df4503 in _server.Client.readSocket (???)
???:?:?: 0x105df77bf in _server.Server.run (???)
???:?:?: 0x105e1d04b in _main.run (???)
???:?:?: 0x105e2374f in _main (???)
???:?:?: 0x195342b97 in ??? (???)
???:?:?: 0x0 in ??? (???)
[1]    23516 abort      ./lightpanda
```

```
$ node index.js https://bring4you.com

Navigating to https://bring4you.com
[]
file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:77
            this._reject(callback, new TargetCloseError('Target closed'));
                                   ^

TargetCloseError: Protocol error (Target.disposeBrowserContext): Target closed
    at CallbackRegistry.clear (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:77:36)
    at #onClose (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:175:25)
    at WebSocket.<anonymous> (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:43:30)
    at callListener (/Users/gianpaj/tmp/lightpanda-fetch/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/Users/gianpaj/tmp/lightpanda-fetch/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emitClose (/Users/gianpaj/tmp/lightpanda-fetch/node_modules/ws/lib/websocket.js:272:10)
    at Socket.socketOnClose (/Users/gianpaj/tmp/lightpanda-fetch/node_modules/ws/lib/websocket.js:1341:15)
    at Socket.emit (node:events:519:28)
    at TCP.<anonymous> (node:net:343:12) {
  cause: ProtocolError
      at <instance_members_initializer> (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:97:14)
      at new Callback (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:101:16)
      at CallbackRegistry.create (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:20:26)
      at Connection._rawSend (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:95:26)
      at Connection.send (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:86:21)
      at CdpBrowser._disposeContext (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:115:32)
      at CdpBrowserContext.close (file:///Users/gianpaj/tmp/lightpanda-fetch/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/BrowserContext.js:135:29)
      at file:///Users/gianpaj/tmp/lightpanda-fetch/index.js:36:15
}

Node.js v22.9.0
```

Same javascript code as in https://github.com/lightpanda-io/browser/issues/619

```
./lightpanda version
1015fc09
```

**Comment by krichprollsch** [comment]
@gianpaj thanks for your feedback, created #1264 to follow up.
